<?php $menu = $this->getDataValue('menu'); ?>
<h2><?php echo $menu->menu_id ? 'Edit Menu' : 'Add Menu'; ?></h2>
<form action="index.php?c=menu&a=save" method="post">
    <input type="hidden" name="menu[menu_id]" value="<?php echo $menu->menu_id; ?>">
    <table border="1" width="100%">
        <tr>
            <td>Name</td>
            <td><input type="text" name="menu[name]" value="<?php echo $menu->name; ?>"></td>
        </tr>
        <tr>
            <td>Controller</td>
            <td><input type="text" name="menu[controller]" value="<?php echo $menu->controller; ?>"></td>
        </tr>
        <tr>
            <td>Action</td>
            <td><input type="text" name="menu[action]" value="<?php echo $menu->action; ?>"></td>
        </tr>
        <tr>
            <td>Status</td>
            <td>
                 <select name="menu[status]">
                    <?php foreach($menu->getStatusOption() as $key => $value): ?>
                        <option value="<?php echo $key; ?>" <?php echo $menu->status == $key ? 'selected' : ''; ?>><?php echo $value; ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>Position</td>
            <td><input type="text" name="menu[position]" value="<?php echo $menu->position; ?>"></td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
                <a href="index.php?c=menu&a=list">Cancel</a>
            </td>
        </tr>
    </table>
</form>