<h2>Category List</h2>
<a href="<?php echo $this->getUrl('edit', 'category', [], true); ?>">Add New Category</a>
<br><br>

<table border="1" width="100%">
    <tr>
        <th>ID</th>
        <th>Parent Category</th>
        <th>Name</th>
        <th>Status</th>
        <th>Created Date</th>
        <th>Updated Date</th>
        <th>Actions</th>
    </tr>
    <?php if (!empty($this->getData())): ?>
        <?php foreach ($this->getData() as $category): ?>
            <tr>
                <td><?php echo $category->category_id; ?></td>
                <td>
                    <?php echo $category->getPathNames(); ?>
                </td>
                <td><?php echo $category->name; ?></td>
                <td><?php echo $category->getStatus(); ?></td>
                <td><?php echo $category->created_date; ?></td>
                <td><?php echo $category->updated_date; ?></td>
                <td>
                    <a href="<?php echo $this->getUrl('edit', 'category', ['id' => $category->category_id], true); ?>">Edit</a> |
                    <a href="<?php echo $this->getUrl('delete', 'category', ['id' => $category->category_id], true); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="9">No records found.</td>
        </tr>
    <?php endif; ?>
</table>