<?php $module = $this->getData('module'); ?>

<h2>Edit Module</h2>
<form action="<?php echo $this->getUrl('save'); ?>" method="post">
    <input type="hidden" name="module[module_id]" value="<?php echo $module->module_id; ?>">
    <label for="name">Name:</label>
    <input type="text" name="module[name]" id="name" value="<?php echo $module->name; ?>"><br><br>
    <label for="code">Code:</label>
    <input type="text" name="module[code]" id="code" value="<?php echo $module->code; ?>"><br><br>
    <label for="status">Status:</label>
    <select name="module[status]">
        <?php foreach($module->getStatusOption() as $key => $value): ?>
            <option value="<?php echo $key; ?>" <?php echo $module->status == $key ? 'selected' : ''; ?>><?php echo $value; ?></option>
        <?php endforeach; ?>
    </select><br><br>
    <input type="submit" value="Save">
    <a href="<?php echo $this->getUrl('list'); ?>">Back</a>
</form>