<?php $data = $this->getDataValue('module'); ?>

<h2>Edit Module</h2>
<form action="index.php?c=module&a=save" method="post">
    <input type="hidden" name="module[module_id]" value="<?php echo $data->module_id; ?>">
    <label for="name">Name:</label>
    <input type="text" name="module[name]" id="name" value="<?php echo $data->name; ?>"><br><br>
    <label for="code">Code:</label>
    <input type="text" name="module[code]" id="code" value="<?php echo $data->code; ?>"><br><br>
    <label for="status">Status:</label>
    <select name="module[status]">
        <?php foreach($data->getStatusOption() as $key => $value): ?>
            <option value="<?php echo $key; ?>" <?php echo $data->status == $key ? 'selected' : ''; ?>><?php echo $value; ?></option>
        <?php endforeach; ?>
    </select><br><br>
    <input type="submit" value="Save">
</form>