

<h2>Module List</h2>
<a href="<?php echo $this->getUrl('edit', 'module'); ?>">Add New Module</a>
<br><br>

<table border="1" width="100%">
    <tr>
        
        <th>Name</th>
        <th>Code</th>
        <th>Status</th>
        <th>Actions</th>
    </tr>
    <?php if ($this->getData('modules')): ?>
        <?php foreach ($this->getData('modules') as $module): ?>
            <tr>
                <td><?php echo $module->name; ?></td>
                <td><?php echo $module->code; ?></td>
                <td><?php echo $module->getStatus(); ?></td>
                <td>
                    <a href="<?php echo $this->getUrl('edit', 'module', ['id' => $module->module_id]); ?>">Edit</a> |
                    <a href="<?php echo $this->getUrl('delete', 'module', ['id' => $module->module_id]); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="9">No records found.</td>
        </tr>
    <?php endif; ?>
</table>