<?php $data = $this->getDataValue('customer_group'); ?>

<h2><?php echo $data->customer_group_id ? 'Edit Customer Group' : 'Add New Customer Group'; ?></h2>

<form method="POST" action="index.php?c=customer_group&a=save">
    <input type="hidden" name="customer_group[customer_group_id]" value="<?php echo $data->customer_group_id; ?>">

    <table border="1" width="100%">
        <tr>
            <td>Name</td>
            <td><input type="text" name="customer_group[group_name]" value="<?php echo $data->group_name; ?>"></td>
        </tr>
        <tr>
            <td>Status</td>
            <td>
                 <select name="customer_group[status]">
                    <?php foreach($data->getStatusOption() as $key => $value): ?>
                        <option value="<?php echo $key; ?>" <?php echo $data->status == $key ? 'selected' : ''; ?>><?php echo $value; ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
                <a href="index.php?c=customer_group&a=list">Back</a>
            </td>
        </tr>
    </table>
</form>