<h2>Customer Group List</h2>
<a href="<?php echo $this->getUrl('edit', 'customer_group'); ?>">Add New Customer Group</a>
<br><br>

<table border="1" width="100%">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Status</th>
        <th>Created Date</th>
        <th>Updated Date</th>
        <th>Actions</th>
    </tr>
    <?php if ($this->getData()): ?>
        <?php foreach ($this->getData() as $customer_group): ?>
            <tr>
                <td><?php echo $customer_group->customer_group_id; ?></td>
                <td><?php echo $customer_group->group_name; ?></td>
                <td><?php echo $customer_group->getStatus(); ?></td>
                <td><?php echo $customer_group->created_date; ?></td>
                <td><?php echo $customer_group->updated_date; ?></td>
                <td>
                    <a href="<?php echo $this->getUrl('edit', 'customer_group', ['id' => $customer_group->customer_group_id]); ?>">Edit</a> |
                    <a href="<?php echo $this->getUrl('delete', 'customer_group', ['id' => $customer_group->customer_group_id]); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="9">No records found.</td>
        </tr>
    <?php endif; ?>
</table>
