<h2>Product List</h2>
<a href="<?php echo $this->getUrl('edit', 'product', [], true); ?>">Add New Product</a>
<br><br>

<table border="1" width="100%">
    <tr>
        <th>ID</th>
        <th>Category</th>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Description</th>
        <th>Status</th>
        <th>Media</th>
        <th>Created Date</th>
        <th>Updated Date</th>
        <th>Actions</th>
    </tr>
    <?php if ($products = $this->getData()): ?>
        <?php foreach ($products as $product): ?>
            <tr>
                <td><?php echo $product->product_id; ?></td>
                <td><?php echo $product->category_name; ?></td>
                <td><?php echo $product->name; ?></td>
                <td><?php echo $product->quantity; ?></td>
                <td><?php echo $product->price; ?></td>
                <td><?php echo $product->description; ?></td>
                <td><?php echo $product->getStatus(); ?></td>
                <td>
                    <a href="<?php echo $this->getUrl('edit', 'product_media', ['id' => $product->product_id]); ?>"><?php echo $product->media_count; ?></a>
                </td>
                <td><?php echo $product->created_date; ?></td>
                <td><?php echo $product->updated_date; ?></td>
                <td>
                    <a href="<?php echo $this->getUrl('edit', 'product', ['id' => $product->product_id], true); ?>">Edit</a> |
                    <a href="<?php echo $this->getUrl('delete', 'product', ['id' => $product->product_id], true); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="9">No records found.</td>
        </tr>
    <?php endif; ?>
</table>