<div class="header">
    <?php $menus = $this->getMenu(); ?>
    <div class="menu">
        <?php if($menus): ?>
            <?php foreach($menus as $menu): ?>
                <a href="<?php echo $this->getUrl($menu->action, $menu->controller); ?>"><?php echo $menu->name; ?></a>
            <?php endforeach; ?>
        <?php endif; ?>
        <a href="<?php echo $this->getUrl('logout', 'admin'); ?>" class="logout">Logout</a>
    </div>
    <hr>
</div>