<h2>Product Media</h2>
<?php $media = $this->getData('media'); ?>

<form action="<?php echo $this->getUrl('save', 'product_media', ['id' => $this->getDataValue('product_id')]); ?>" method="POST">
    <table border="1" width="100%">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product Id</th>
                    <th>Alt Text</th>
                    <th>Base</th>
                    <th>Thumb</th>
                    <th>Small</th>
                    <th>Gallary</th>
                    <th>Enabled</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php if (!empty($media)): ?>
                    <?php foreach ($media as $item): ?>
                        <tr>
                            <td><img src="app/media/<?php echo $item->file_path; ?>" alt="Image" style="width:100px; height: 80px; "></td>
                           
                            <td><?php echo $item->product_id; ?></td>
                           
                            <td><input type="text" name="item[<?php echo $item->product_media_id; ?>][alt_text]" value="<?php echo htmlspecialchars($item->alt_text ?? ''); ?>"></td>
                           
                            <td><input type="radio" name="base" value="<?php echo $item->product_media_id; ?>" <?php echo ($item->base) ? 'checked' : ''; ?>></td>
                           
                            <td><input type="radio" name="thumb" value="<?php echo $item->product_media_id; ?>" <?php echo ($item->thumb) ? 'checked' : ''; ?>></td>
                           
                            <td><input type="radio" name="small" value="<?php echo $item->product_media_id; ?>" <?php echo ($item->small) ? 'checked' : ''; ?>></td>
                           
                            <td><input type="checkbox" name="item[<?php echo $item->product_media_id; ?>][gallery]" value="1" <?php echo ($item->gallery) ? 'checked' : ''; ?>></td>
                           
                            <td><input type="checkbox" name="item[<?php echo $item->product_media_id; ?>][status]" value="1" <?php echo ($item->status) ? 'checked' : ''; ?>></td>
                           
                            <td><a href="<?php echo $this->getUrl('product_media', 'delete', ['id' => $item->product_media_id]); ?>">Remove</a></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="8">No records found.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    <br>
    <input type="submit" value="Update">
    <a href="<?php echo $this->getUrl('list', 'product'); ?>">Back to Products</a>
</form>
    <div>
        <form action="<?php echo $this->getUrl('upload', 'product_media', ['id' => $this->getDataValue('product_id')]); ?>" method="POST" enctype="multipart/form-data">
            <input type="file" name="file_path">
            <button type="submit">Upload</button>
        </form>
    </div>
</div>