<!DOCTYPE html>
<html>
<head>
    <title>My Application</title>
    <link rel="stylesheet" href="<?php echo $this->getBaseUrl('assets/css/style.css'); ?>">
</head>
<body style="height: 100vh;">
    <table width="100%" height="100%">
        <tr>
            <td style="vertical-align: middle">
                <?php $this->getChild('content')->render(); ?>
            </td>
        </tr>
    </table>

</body>
</html>
