<!DOCTYPE html>
<html>

<head>
  <title>My Application</title>
  <link rel="stylesheet" href="<?php echo $this->getBaseUrl('assets/css/style.css'); ?>">

</head>

<body style="height: 100vh;">
  <table border="1" width="100%" height="100%">
    <tr height="20%">
      <td>
        <?php $this->getChild('header')->render(); ?>
      </td>
    </tr>
    <tr>
      <?php if(!empty($_SESSION['message'])): ?>
      <td>
      <?php $this->getChild('message')->render(); ?>
      </td>
      <?php endif; ?>
    </tr>
    <tr height="60%">
      <td>
        <?php $this->getChild('content')->render(); ?>
      </td>
    </tr>
    <tr height="20%">
      <td>
        <?php $this->getChild('footer')->render(); ?>
      </td>
    </tr>
  </table>
</body>

</html>